name: tinano_generator
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  source_gen:
  collection:
  meta:
  code_builder:
  build: ^1.0.0
  build_config:

dev_dependencies:
  test: ^1.0.0
